### ISSUE TITLE
Upgrade from previous version

### ISSUE THREAD

**Issue by YuriGor** [haurit/now-compare_tool#14]
Hi Tom, great to see you moved to hithub, this way you have more chances to get help from community :)
BTW would be helpful to have hints on update procedure, especially from previous version published as update set directly on snow forum.

**Comment by haurit** [comment]
Hi Yuri,
Unfortunately there is no "upgrade" path as the new version is a completely separated scoped application. You would have to install the new version and re-configure the compare configuration. If you have created many and complex configurations I can write a script to transition the records over (the db structure is quite similar), but most probably it's less effort to just manually recreate the configuration. After the transition the old Scoped Application including the "automagically" created Global Scoped script "CrossInstanceCompareGlobal" can be deleted.
Thanks for raising the issue, please let me know if you need help with the transition or if this is fine for you.
Tom

**Comment by YuriGor** [comment]
Thanks, it's ok to drop all the data. 
I was asking more in terms of installation process, if there are some conflicts possible/special steps required.
So basically we just backout update set with beta version and deploy new one from this repo.
Thanks for reply.
