### ISSUE TITLE
Weird issue on sys_plugins table.

### ISSUE THREAD

**Issue by YuriGor** [haurit/now-compare_tool#26]
Hi, help needed. Compare tool works as expected on other tables, but when I try to compare sys_plugins table it complains about wrong credentials:

> Error: Failed to get remote list (Right) with error Method failed: (/api/now/stats/sys_plugins) with code: 403 - Forbidden username/password combo

I do local to remote list comparison.
In collection alias I use my own admin username/pwd, and it works fine with other tables.

Have you ever tried compare plugins, was it working fine or some extra tweaks are needed?

**Comment by haurit** [comment]
Hi Yuri,
Yes, I noticed the same. To workaround this I usually compare the v_plugin db view instead of sys_plugins.

Actually in the Community Article there is an comment where I reply to Daniel A--C comment on how to compare Custom Apps, Plugins, Store Apps etc. 
Hope this helps!
Tom

**Comment by YuriGor** [comment]
Thank you, it works with v_plugin
For those who will land to this issue, here is a link:
https://www.servicenow.com/community/in-other-news/compare-tool-easily-diff-instances-and-snapshots/ba-p/2759060
First two comments.
